<?php

/**
 * Implements hook_init().
 */
function fuc_init() {
  return;

  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'raffle')
    ->entityCondition('bundle', 'raffle');

  $result = $query->execute();

  if (isset($result['raffle'])) {
    entity_delete_multiple('raffle', array_keys($result['raffle']));
  }

//  raffle_save(array(
//    'raffle_id' => 71,
//    'participants' => array(
//      6,
//      3,
//      5,
//      4,
//    ),
//    'matches' => array(
//      array(
//        'teams' => array(
//          array(
//            'player_ids' => array(
//              6,
//              2,
//            ),
//          ),
//          array(
//            'player_ids' => array(
//              4,
//              5,
//            ),
//          ),
//        ),
//      ),
//      array(
//        'teams' => array(
//          array(
//            'player_ids' => array(
//              6,
//              4,
//            ),
//          ),
//          array(
//            'player_ids' => array(
//              3,
//              5,
//            ),
//          ),
//        ),
//      ),
//    ),
//  ));
}
