<?php

/**
 * Implements hook_menu().
 */
function statistics_menu() {
  $items = array();

  $items['statistics'] = array(
    'page callback' => 'statisitcs_page',
    'access callback' => TRUE,
  );

  return $items;
}

function statisitcs_page() {
  return '';
}

/**
 * Implements hook_views_api().
 */
function statistics__views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'statistics') . '/views',
  );
}
